name: Build Downkyi EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install NuGet CLI
        uses: nuget/setup-nuget@v1

      - name: Restore packages (packages.config & PackageReference)
        run: |
          nuget restore src/Downkyi.sln
          dotnet restore src/Downkyi.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution in Release (Any CPU, include win RID)
        run: msbuild src/Downkyi.sln /m /p:Configuration=Release /p:Platform="Any CPU" /p:RuntimeIdentifiers=win

      - name: Upload EXE and DLLs
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Downkyi-Release
          path: |
            src/DownKyi/bin/Release/DownKyi.exe
            src/DownKyi/bin/Release/*.dll
