name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release] # 只构建 Release 版本

    runs-on: windows-latest

    env:
      Solution_Name: src/Downkyi.sln # 解决方案文件路径

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # 确保与项目兼容的 .NET 版本

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: dotnet restore $env:Solution_Name

    - name: Build the solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload Executable Artifacts
      if: success() # 仅在构建成功时上传
      uses: actions/upload-artifact@v4
      with:
        name: DownKyi Executable (${{ matrix.configuration }})
        # 通常主项目的输出会在其 bin/Release 目录下，具体子目录可能依赖于目标框架
        # 例如 src/DownKyi/bin/Release/net8.0-windows/
        # 我们先尝试上传整个 Release 输出目录，您可以在里面找到 .exe
        path: src/DownKyi/bin/${{ matrix.configuration }}/
