name: Build Downkyi EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup NuGet CLI
      uses: nuget/setup-nuget@v1

    - name: Restore all NuGet packages (packages.config support)
      run: nuget restore src/Downkyi.sln

    - name: Build solution in Release
      run: dotnet msbuild src/Downkyi.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload EXE and DLL output
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Downkyi-Release
        path: |
          src/DownKyi/bin/Release/
          src/DownKyi/bin/Release/net8.0-windows/
